### ISSUE TITLE
HsSyck doesn't compile with GHC 7.8.1-rc1

### ISSUE THREAD

**Issue by audreyt** [audreyt/hssyck#3]
the current version of HsSyck doesn't compile with GHC 7.8.1-rc1,
probably because of a change in the Generics interface:

 Data/Yaml/Syck.hsc:42:16:
     Not in scope: 'mkIntConstr'
     Perhaps you meant â€˜mkConstrâ€™ (imported from Data.Generics)

A complete build log is at http://hydra.cryp.to/build/43998/nixlog/2/raw.
